### PR TITLE
Add Community example by meekmusa2

### PR DESCRIPTION
**Pull request by meekMusa2**
How would you rate the usage of the npx create-nillion-app process
Give a rating / 10
9/10

What platform you run your CLI on
Mac / Windows / Linux
Linux

Did you get stuck during the CLI process?
Did you experience any issues while using the latest CLI and were you able to use the template?
Initially had some hitch but the documentation helped

What is your Github repository link
Include the repository you worked on.
https://github.com/meekMusa2/nillion-hacktoberfest

ETH Address (Optional)
0x432d199df4Dee79C53A5BEa50cFE57FD51805c1B

### CODE REVIEW

**Comment by meekMusa2** [comment]
Hi,
This pull request adds my Hacktoberfest contribution to the Examples (Community) section. The project showcases secure addition using Nillion's Nada protocol to demonstrate secret computation. I hope this contribution will be helpful for others looking to explore Nillion's capabilities.

Thank you for considering my contribution!

Best regards,
Abdulquadri

**Comment by crypblizz8** [comment]
Incorrect approach to adding a PR to the repo.

Please follow this approach https://github.com/NillionNetwork/awesome-nillion/pull/3/files

**Comment by meekMusa2** [comment]
resolved, kindly recheck.

**Comment by crypblizz8** [comment]
Great job!

**Pull request merged**
